import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Grouping Webhooks
  guides: [
    "intro",
    {
      type: "category",
      label: "Primeros Pasos",
      collapsed: false,
      items: ["primerospasos/index", "primerospasos/signup", "primerospasos/login", "primerospasos/app"],
    },
    {
      type: "category",
      label: "Autenticación",
      collapsed: true,
      items: ["authentication/index"],
    },
    {
      type: "category",
      label: "Webhooks",
      collapsed: true,
      items: ["webhooks/index", "webhooks/handle-webhooks", "webhooks/events"],
    },
    {
      type: "category",
      label: "Usuarios",
      collapsed: true,
      items: ["users/index"],
    },
    {
      type: "category",
      label: "Préstamos",
      collapsed: true,
      items: ["loans/index"],
    },
    {
      type: "category",
      label: "Comunicación",
      collapsed: true,
      items: ["campaigns/index", "campaigns/list", "campaigns/id", "campaigns/id-analytics", "campaigns/id-emails"],
    },
  ],
};

export default sidebars;
