name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main # Cambia a la rama que prefieras para activar el despliegue

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configuración de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Usa la versión recomendada para Docusaurus

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # 4. Construir el sitio
      - name: Build website
        run: npm run build

      # 5. Asegurar el archivo CNAME
      - name: Add CNAME file
        run: echo 'docs.bemanda.io' > ./build/CNAME

      # 6. Desplegar en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
